name: api-gateway

on:
  push:
    branches: [main]

jobs:
  build-and-push:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2


      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./api-gateway
          push: true
          tags: yourdockerhub/service1:latest

________________________________________
